package com.mycode.crm.settings.mapper;

import com.mycode.crm.settings.domain.User;

import java.util.List;
import java.util.Map;
import java.util.Objects;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sat Sep 09 16:52:39 CST 2023
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账户和密码查询用户
     * @param loginInfo
     * @return
     */
    User selectUserByLoginActAndPwd(Map<String, Object> loginInfo);

    List<User> selectAll();
}